---
tenants:
  MY_FABRIC:
    vrfs:
      default:
        svis:
          30:
            name: 'Thirty'
            tags: ["30"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.30.30.1
            nodes:
              s2-spine1:
                ip_address: 10.30.30.2/24
              s2-spine2:
                ip_address: 10.30.30.3/24
          40:
            name: 'Forty'
            tags: ["40"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.40.40.1
            nodes:
              s2-spine1:
                ip_address: 10.40.40.2/24
              s2-spine2:
                ip_address: 10.40.40.3/24

